ext{
    android = [
            versionCode      : 4,
            versionName      : "1.0.4"
    ]
    dependencies = [

    ]

    appConfig = [

            //TODO 隐私协议
            "privacyUrl": "https://sites.google.com/view/dreamdraw/home/privacy",
            "userUrl"   : "https://sites.google.com/view/dreamdraw/home/terms",
            "VERSIONNAME":android.versionName,

            //TODO 接口环境  日志log开关
            "logSwitch"    : false,

            "ad_LiveTime":"2025-12-06 10:00:00",



            "umID":"",

            //TODO 第三方广告SDK ID
            "TOPON_APPID"           : "h6985a52b7eeb1", //正式 topOne Id
            "TOPON_APPKEY"          : "a3b261770bb14a6bd5239e218241b3c4e", //正式 topOne key
            "AF_APP_KEY"            : "",//appsflyer： XXUDmA5EdsBAiNsrXBzPiY
            "ADJUST_TOKEN"          : "",
            "APPID"                 : "",
            "FISRT_SPLASH"          : "",
            "FIRST_REWORD" : " "
    ]

}