ext{
    android = [
            versionCode      : 4,
            versionName      : "1.0.4"
    ]
    dependencies = [

    ]

    appConfig = [

            //TODO 隐私协议
            "privacyUrl": "https://sites.google.com/view/readerpdf/home/privacy",
            "userUrl"   : "https://sites.google.com/view/readerpdf/home/terms",
            "VERSIONNAME":android.versionName,

            //TODO 接口环境  日志log开关
            "logSwitch"    : false,

            "ad_LiveTime":"2026-07-16 18:00:00",
            "ad_huawei_LiveTime":"2025-12-06 10:00:00",

            "HOST":"",
            "DEBUG_APPID":"",
            "RELEASE_APPID":"",
            "DEBUG_SSK":"",
            "RELEASE_SSK":"",
            "isDebug":"false",
            "buglyId":"",
            "Admob_AppId":"ca-app-pub-3924069160429935~1792826298",

            "umID":"",

            //TODO 第三方广告SDK ID
            "TOPON_APPID"           : "h691eb23982b34", //正式 topOne Id
            "TOPON_APPKEY"          : "abb325d6a80de9f580f2f41dc6a825556", //正式 topOne key
            "TradPlus_ID"           : "FDCD339CDFF8474572167ED535565C11",
            "AF_APP_KEY"            : "",//appsflyer： XXUDmA5EdsBAiNsrXBzPiY
            "ADJUST_TOKEN"          : "z6mizjojl88w",
            "PANGLE_APPID"          : "8830254",// Pangle App ID
            "FISRT_SPLASH"          : "",
            "FIRST_REWORD" : " "
    ]

}
