ext{
    android = [
            versionCode      : 1,
            versionName      : "1.0.1"
    ]
    dependencies = [

    ]

    appConfig = [

            //TODO 隐私协议
            "privacyUrl": "https://sites.google.com/view/horizonweather/home/privacy",
            "userUrl"   : "https://sites.google.com/view/horizonweather/home/terms",
            "VERSIONNAME":android.versionName,

            //TODO 接口环境  日志log开关
            "logSwitch"    : true,

            "ad_LiveTime":"2026-04-22 18:00:00",



            "umID":"",

            //TODO 第三方广告SDK ID
            "TOPON_APPID"           : "", //测试 topOne Id
            "TOPON_APPKEY"          : "", //测试 topOne key
            "AF_APP_KEY"            : "",//appsflyer： XXUDmA5EdsBAiNsrXBzPiY
            "TradPlus_ID"           : "CB94948BA3CBE894EB0558B1E3FFE211",
            "ADJUST_TOKEN"          : "vjjythxozc3k",
            "APPID"                 : "",
            "FISRT_SPLASH"          : "",
            "FIRST_REWORD" : " ",
            "ad_name":"ui.aar",
            // oversea_base_module 需要的字段（测试占位）
            "HOST": "",
            "DEBUG_APPID": "",
            "RELEASE_APPID": "",
            "DEBUG_SSK": "",
            "RELEASE_SSK": "",
            "isDebug": "false",
            "buglyId": "",
            "Admob_AppId": "",
            "ad_huawei_LiveTime": "2025-04-30 10:00:00",
    ]

}