pluginManagement {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://jitpack.io' }
        maven { url 'https://artifact.bytedance.com/repository/pangle' }
        maven { url 'https://developer.huawei.com/repo' }
        maven { url 'https://developer.hihonor.com/repo' }
        maven { url 'https://jfrog.anythinktech.com/artifactory/overseas_sdk' }
        maven { url 'https://jfrog.anythinktech.com/artifactory/debugger' }
        maven { url 'https://android-sdk.is.com/' }
        maven { url 'https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea' }
        maven { url 'https://cboost.jfrog.io/artifactory/chartboost-ads' }
        maven { url 'https://cboost.jfrog.io/artifactory/chartboost-mediation' }
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url 'https://jitpack.io' }
        maven { url 'https://artifact.bytedance.com/repository/pangle' }
        maven { url 'https://developer.huawei.com/repo' }
        maven { url 'https://developer.hihonor.com/repo' }
        maven { url 'https://jfrog.anythinktech.com/artifactory/overseas_sdk' }
        maven { url 'https://jfrog.anythinktech.com/artifactory/debugger' }
        maven { url 'https://android-sdk.is.com/' }
        maven { url 'https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea' }
        maven { url 'https://cboost.jfrog.io/artifactory/chartboost-ads' }
        maven { url 'https://cboost.jfrog.io/artifactory/chartboost-mediation' }
        flatDir { dirs 'libs' }
    }
}

rootProject.name = 'OverSeasWhiteBag'

include ':app'

include ':toolsbox'
project(':toolsbox').projectDir = file('./toolsbox_moduel/toolsbox')

include ':setting'
project(':setting').projectDir = file('./third-module/setting')

include ':build_tools'
project(':build_tools').projectDir = file('./third-module/build_tools/build_tools')

include ':stringfogLib'
project(':stringfogLib').projectDir = file('./third-module/stringfogLib')

include ':oversea_base_module'
project(':oversea_base_module').projectDir = file('./oversea_base_module')

include ':oversea_common_library'
project(':oversea_common_library').projectDir = file('./oversea_base_module/oversea_common_library')

include ':oversea_base_power'
project(':oversea_base_power').projectDir = file('./oversea_base_module/oversea_base_power')

include ':aar_library:aar_name'
