pluginManagement {
    repositories {
//    gradlePluginPortal()

        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url "https://jitpack.io" }
        maven { url "https://artifact.bytedance.com/repository/pangle" }
        google()
        mavenCentral()
        maven { url 'https://developer.huawei.com/repo' }
        maven { url 'https://developer.hihonor.com/repo' }
        //Ironsource
        maven {
            url "https://android-sdk.is.com/"
        }

        //Pangle
        maven {
            url "https://artifact.bytedance.com/repository/pangle"
        }

        //Huawei
        maven {
            url "https://developer.huawei.com/repo/"
        }

        //Mintegral
        maven {
            url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea"
        }

        //Chartboost
        maven {
            url "https://cboost.jfrog.io/artifactory/chartboost-ads"
        }
        maven {
            url "https://cboost.jfrog.io/artifactory/chartboost-mediation"
        }
    }
}


dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
//    gradlePluginPortal()

        maven { url 'https://maven.aliyun.com/repository/central' }
        maven { url 'https://maven.aliyun.com/repository/google' }
        maven { url 'https://maven.aliyun.com/repository/public' }
        maven { url 'https://maven.aliyun.com/repository/gradle-plugin' }
        maven { url "https://jitpack.io" }
        maven { url "https://artifact.bytedance.com/repository/pangle" }
        google()
        mavenCentral()
        maven { url 'https://developer.huawei.com/repo' }
        maven { url 'https://developer.hihonor.com/repo' }
        flatDir {
            dirs 'libs'
        }
        //Ironsource
        maven {
            url "https://android-sdk.is.com/"
        }

        //Pangle
        maven {
            url "https://artifact.bytedance.com/repository/pangle"
        }

        //Huawei
        maven {
            url "https://developer.huawei.com/repo/"
        }

        //Mintegral
        maven {
            url "https://dl-maven-android.mintegral.com/repository/mbridge_android_sdk_oversea"
        }

        //Chartboost
        maven {
            url "https://cboost.jfrog.io/artifactory/chartboost-ads"
        }
        maven {
            url "https://cboost.jfrog.io/artifactory/chartboost-mediation"
        }
    }
}


rootProject.name = "OverSeasWhiteBag"
include ':app'
include ':setting'
project(':setting').projectDir = file('./third-module/setting')


include(':build_tools')
project(':build_tools').projectDir =file('./third-module/build_tools/build_tools')

include(':toolsbox')
project(':toolsbox').projectDir = file('./toolsbox_moduel/toolsbox')



include(':sharedPreferences')
project(':sharedPreferences').projectDir = file('./third-module/sharedPreferences')


include(':oversea_base_module')
project(':oversea_base_module').projectDir = file('./oversea_base_module')


include(":aar_library:aar_name")