plugins {
    id 'java'
}

repositories {
    google()
    mavenCentral()
    mavenLocal()
    maven { url "https://jitpack.io" }
}

dependencies {
    implementation gradleApi()
    implementation('com.github.CodingGay.BlackObfuscator:dex-tools:2.1') {
        exclude group: 'com.google.guava', module: 'guava'
    }
    implementation 'com.google.guava:guava:32.0.1-jre'
    // 自定义算法实现依赖库
    implementation 'com.github.megatronking.stringfog:interface:5.0.0'
}
